<template>
  <img :src="imageData" alt="" />
</template>

<style scoped lang="less">

</style>

<script>
// this component is deprecated due to the component itself will
// generate a base64 qrcode image and put it in <img>.
// but wechat browser can not download the base64 images.
import qr from 'qr.js'

const canvasElem = document.createElement('canvas')

// options = {
//   value: "",
//   width: 0,
//   height: 0,
//   margin: 0,
//   canvasElem
// }
//
const generateQrcodeCanvas = function (options) {
  const value = options.value
  const width = options.width
  const height = options.height
  const margin = options.margin
  const canvasElem = options.canvasElem

  let canvas = canvasElem || document.createElement('canvas')
  canvas.width = width + margin * 2
  canvas.height = height + margin * 2
  const ctx = canvas.getContext('2d')
  const cells = qr(value).modules // the black/white dots generated by qr.js
  const length = cells.length
  const tileW = width / length
  const tileH = height / length

  // fill the white blank
  ctx.fillStyle = '#fff'
  ctx.fillRect(0, 0, canvas.width, canvas.height)

  ctx.clearRect(margin, margin, width, height)

  // draw canvas
  for (let r = 0; r < length; r += 1) {
    const row = cells[r]
    for (let c = 0; c < length; c += 1) {
      ctx.fillStyle = row[c] ? '#000' : '#fff'
      const w = (Math.ceil((c + 1) * tileW) - Math.floor(c * tileW))
      const h = (Math.ceil((r + 1) * tileH) - Math.floor(r * tileH))
      ctx.fillRect(margin + Math.round(c * tileW), margin + Math.round(r * tileH), w, h)
    }
  }

  return canvas
}

const getBase64ImageData = function (canvas, imageType) {
  imageType = imageType || 'image/png'
  return canvas.toDataURL(imageType)
}

export default {
  props: {
    value: {
      type: String,
      required: true
    },
    width: {
      type: Number,
      required: false,
      default: 64
    },
    height: {
      type: Number,
      required: false,
      default: 64
    },
    margin: { // white margin of qrcode
      type: Number,
      required: false,
      default: 0
    }
  },
  computed: {
    qrcodeStyle () {
      return {
        width: `${this.width}px`,
        height: `${this.height}px`
      }
    },
    imageData () {
      const canvas = generateQrcodeCanvas({
        value: this.value,
        width: this.width,
        height: this.height,
        canvasElem: canvasElem,
        margin: this.margin
      })
      return getBase64ImageData(canvas)
    }
  }
}
</script>
